app:
  build: .
  command: python -u wsgi.py
  ports:
    - "5000:5000"
  volumes:
    - .:app
  link:
    - db
db:
  image: mongo:latest
  hostname: abs
  environment:
    -MONGO_INITDB_DATABASE=abs_tracking_db
    -MONGO_INITDB_ROOT_USERNAME=root
    -MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
    - ./init-db.js:/docker-entrypoint-initdb.d/initdb.js:ro
  ports:
    - 27017:27017